stages:
    - build
    - test
    - code-quality

# ----- Build stage
.build-setup-composer: &build-setup-composer
    script:
        - curl -sS https://getcomposer.org/installer | php
        - php composer.phar install --prefer-dist --optimize-autoloader --no-interaction --no-progress

.build-job-shared: &build-job-shared
    stage: build
    <<: *build-setup-composer
    cache:
        key: "$CI_JOB_NAME"
        paths:
            - vendor/
    artifacts:
        expire_in: 1 hrs
        paths:
            - vendor/

build:php-7.1:
    image: php:7.1-alpine
    <<: *build-job-shared

build:php-7.2:
    image: php:7.2-alpine
    <<: *build-job-shared

# ----- Test stage
.test-run-phpunit: &test-run-phpunit
    script:
        - php -d memory_limit=256M vendor/bin/phpunit

.test-job-shared: &test-job-shared
    stage: test
    <<: *test-run-phpunit

test:php-7.1:
    image: php:7.1-alpine
    <<: *test-job-shared
    dependencies:
        - build:php-7.1

test:php-7.2:
    image: php:7.2-alpine
    <<: *test-job-shared
    dependencies:
        - build:php-7.2

# ----- Code quality analysis stage
code-quality:code-coverage:
    image: php:7.1-alpine
    stage: code-quality
    before_script:
        - apk add --no-cache autoconf
        - apk add --no-cache gcc
        - apk add --no-cache g++
        - apk add --no-cache make
        - pecl install xdebug
        - docker-php-ext-enable xdebug
    script:
        - php -d memory_limit=512M vendor/bin/phpunit --coverage-text --colors=never --coverage-html=coverage
    artifacts:
        expire_in: 1 weeks
        paths:
            - coverage/
    dependencies:
        - build:php-7.1
